// Cross-platform parity test for the V1+V2 DNA signature codec.
//
// Fixtures live under test/fixtures/bgp-parity/ and are mirrored byte-for-byte
// from the desktop repo (commit fc22196 on ovadeus/bgp-mission-control-app-macos).
// They were generated by desktop's scripts/generate-bgp-fixture.js. The
// manifest.json schema is documented in WEB_SYNC_REPLY_002.md.
//
// What we assert per fixture (and why):
//   1. parseBgpFile(content) returns non-null — the file is well-formed.
//   2. decoded.{format, version, signature, beliefSegment, fullDna,
//      demographicPrefix} match the manifest's expected block — desktop's
//      decoder and web's decoder agree on what each fixture represents.
//   3. The in-file `expected` block equals the manifest's expected block —
//      belt-and-suspenders consistency check on desktop's generator.
//   4. Round-trip RE-ENCODE: feeding inputs.v*Full.value back through web's
//      encodeAnonymous / encodeSigned reproduces the signature byte-for-byte.
//      This is the strongest parity guarantee — it proves both sides compute
//      the same SHA-256 checksum and slice the same belief segment.

import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import {
  parseBgpFile,
  encodeAnonymous,
  encodeSigned,
  checksum,
} from '../src/dnaSignature';

const __dirname = dirname(fileURLToPath(import.meta.url));
const FIXTURES_DIR = join(__dirname, 'fixtures', 'bgp-parity');

const manifest = JSON.parse(
  readFileSync(join(FIXTURES_DIR, 'manifest.json'), 'utf-8'),
);

type FixtureName = 'v1-anonymous' | 'v1-signed' | 'v2-anonymous' | 'v2-signed';
const FIXTURE_NAMES: FixtureName[] = [
  'v1-anonymous',
  'v1-signed',
  'v2-anonymous',
  'v2-signed',
];

describe('cross-platform .bgp parity (desktop fixtures)', () => {
  it('manifest schemaVersion is the version this test was written against', () => {
    assert.equal(
      manifest.schemaVersion,
      2,
      'desktop bumped manifest.schemaVersion — review WEB_SYNC_REPLY_*.md and update this test',
    );
    assert.equal(manifest.generatedBy, 'desktop');
    assert.equal(manifest.inputs.v1Full.length, 140);
    assert.equal(manifest.inputs.v2Full.length, 265);
  });

  for (const name of FIXTURE_NAMES) {
    describe(name, () => {
      const fixture = manifest.fixtures[name];
      const fileContent = readFileSync(join(FIXTURES_DIR, fixture.filename), 'utf-8');
      const fileObj = JSON.parse(fileContent);
      const expected = fixture.expected;

      it('parseBgpFile returns a valid ParsedSignature', async () => {
        const decoded = await parseBgpFile(fileContent);
        assert.notEqual(decoded, null, 'parseBgpFile returned null');
      });

      it('decoded fields match the manifest expected block', async () => {
        const decoded = (await parseBgpFile(fileContent))!;
        assert.equal(decoded.format, expected.format, 'format mismatch');
        assert.equal(decoded.version, expected.version, 'version mismatch');
        assert.equal(decoded.signature, expected.signature, 'signature mismatch');
        assert.equal(decoded.beliefSegment, expected.beliefSegment, 'beliefSegment mismatch');

        if (fixture.type === 'signed') {
          assert.equal(decoded.fullDna, expected.fullDna, 'fullDna mismatch');
          assert.notEqual(decoded.demographicPrefix, null, 'demographicPrefix should be present');
          // demographicPrefix is parsed into a structured object on web; the
          // desktop manifest stores the raw 16-char string. Reconstruct and
          // compare.
          const dp = decoded.demographicPrefix!;
          const reconstructed =
            dp.century + dp.birthYear + dp.birthMonth + dp.birthDay +
            dp.sex + dp.countryCode + dp.zipCode;
          assert.equal(reconstructed, expected.demographicPrefix, 'demographicPrefix mismatch');
        } else {
          assert.equal(decoded.fullDna, null, 'anonymous should have null fullDna');
          assert.equal(decoded.demographicPrefix, null, 'anonymous should have null demographicPrefix');
        }
      });

      it('checksum recomputation matches expected', async () => {
        // Recompute the checksum from the payload (full DNA for signed,
        // belief segment for anonymous) using web's checksum() and assert
        // it matches the 4-char checksum in the expected signature.
        const payload =
          fixture.type === 'signed' ? expected.fullDna : expected.beliefSegment;
        const recomputed = await checksum(payload);
        assert.equal(recomputed, expected.checksum, 'checksum mismatch');
      });

      it('in-file expected block equals manifest expected block', () => {
        // Belt-and-suspenders: desktop embeds the same `expected` object
        // inside each .bgp file. They must agree.
        assert.deepEqual(fileObj.expected, expected, 'in-file vs manifest expected block diverge');
      });

      it('round-trip re-encode reproduces the signature byte-for-byte', async () => {
        // The strongest parity assertion. Feed desktop's raw input DNA
        // (manifest.inputs.v*Full.value) into web's encoder and check the
        // result equals the fixture's signature. If this passes, both sides
        // agree on slicing AND SHA-256 checksum byte-for-byte.
        const fullDna =
          fixture.version === 1 ? manifest.inputs.v1Full.value : manifest.inputs.v2Full.value;
        const reEncoded =
          fixture.type === 'signed'
            ? await encodeSigned(fullDna)
            : await encodeAnonymous(fullDna);
        assert.equal(reEncoded, expected.signature, 'web re-encode does not match desktop fixture');
      });
    });
  }
});
